name: enn583
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - nbconvert
  - jupyterlab
  - numpy
  - matplotlib
  - opencv
  - roboticstoolbox-python
  - scikit-image
  - pandas
  - torchvision

