# ###################################################################################################
# IMPORTANT:                                                                                        #
# DO NOT EDIT THIS FILE.                                                                            #
#                                                                                                   #
# This file is used by the autograder to run your visual odometry code on a KITTI sequence.         #
#                                                                                                   #
# You should implement the `visual_odometry` function in `src/visual_odometry.py`.                  #
# ###################################################################################################    

import argparse
import os
from pathlib import Path
import sys

SRC_DIR = Path(__file__).resolve().parents[1] / "src"
SUPPORT_DIR = Path(__file__).resolve().parents[1] / "support"
sys.path.insert(0, str(SUPPORT_DIR))
sys.path.insert(0, str(SRC_DIR))

import visual_odometry as vo
import kitti_utils as kitti
from autograder import Autograder


def main():
    parser = argparse.ArgumentParser(description="Run visual odometry on a KITTI sequence.")
    parser.add_argument("--sequence", type=str, default='2011_09_26_drive_0035', help="KITTI sequence name (e.g. 2011_09_26_drive_0035)")
    parser.add_argument("--data-dir", type=str, default=None, help="Optional data directory for KITTI dataset")
    parser.add_argument(
        "--with-ground-truth",
        action="store_true",
        help="Instructor option: expose ground-truth poses to the implementation.",
    )
    args = parser.parse_args()

    if args.data_dir is not None:
        os.environ["ENN583_DATA_DIR"] = str(Path(args.data_dir).expanduser().resolve())

    full_dataset = kitti.load_kitti_dataset(name=args.sequence)
    dataset = full_dataset.student_view(
        include_ground_truth=args.with_ground_truth
    )

    print(
        f"\nCalling student code with {dataset.frame_count} frames "
        f"from {args.sequence}.\n"
    )
    try:
        results = vo.visual_odometry(dataset=dataset)
    except Exception as e:
        print(f"\n{'='*80}\nError while running student code: {e}. \nPlease check your implementation and make sure it runs without errors.\nFull error messsage below.\n{'='*80}\n")           
        raise       

    
    # ============================================================================================================================
    # Now the autograder will evaluate your result and return your grade    
    autograder = Autograder(results)
    print("\nAutograder finished checking the results. Please check the output above for any errors or feedback from the autograder.\n")
    if not autograder.passed:
        raise SystemExit(1)

if __name__ == "__main__":
    main()
